### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by gogasebi** [QuickBlox/ios-quickblox-sdk#5]
The privacy manifest required by Apple is missing. From 1 May we have to send it for every release we send to the app store.

**Comment by IlliaChemolosov** [comment]
@gogasebi  Hello,

We've noticed that you've encountered the following issue and are already actively working on a solution. The release containing the fix is scheduled for this month, and we are committed to completing it within the next two weeks.

**Comment by IlliaChemolosov** [comment]
Privacy manifest added from Quickblox iOS SDK version 2.20.0 and QuickbloxWebRTC SDK version 3.1.0
